# Generated by Django 5.2.1 on 2025-07-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
