# Generated by Django 5.2 on 2025-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TunepsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_consultation', models.CharField(max_length=255, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('date_publication', models.DateField()),
                ('intitulé_projet', models.TextField()),
                ('date_expiration', models.DateField()),
                ('epBidMasterId', models.CharField(max_length=255)),
                ('lien', models.URLField()),
            ],
        ),
    ]
