# Generated by Django 5.2.1 on 2025-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunisurfOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(max_length=255, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('date_expiration', models.DateField()),
                ('intitule_projet', models.TextField()),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tunepsoffer',
            name='is_filtered',
            field=models.BooleanField(default=False),
        ),
    ]
