# Generated by Django 5.2.1 on 2025-07-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_tunisurfoffer_tunepsoffer_is_filtered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TunisurfOffer',
        ),
        migrations.RemoveField(
            model_name='tunepsoffer',
            name='is_filtered',
        ),
    ]
